version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: financial_organizer
    restart: always
    environment:
      POSTGRES_DB: financial_organizer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
